version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "awslocal secretsmanager list-secrets"
        ]
      timeout: 60s
      interval: 5s
      retries: 15
